### ISSUE TITLE
Choose a fancy color on hovering effect

### ISSUE THREAD

**Issue by Ak-ram** [Ak-ram/Hey-Pin-Menu#1]

**Comment by abitsalihu** [comment]
@Ak-ram I would like to work on this issue. :)

**Comment by Ak-ram** [comment]
@abitsalihu then go ahead

**Comment by abitsalihu** [comment]
@Ak-ram should I change the body bg aswell, or just the hover effect? Becasue it's hard to find a fancy color with a yellow bg.

**Comment by Ak-ram** [comment]
@abitsalihu Certainly, you are welcome to make the necessary adjustments to get matching hues.
